name: Build test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Build Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: false
